
import org.junit.Test;


import java.io.FileNotFoundException;
import java.util.List;

import static org.junit.Assert.*;

public class MainTest {  // Попытка создания теста с JUnit,  однако он не работает т.к. изначально требует
                         // добавление исключения в метод, что не дает результата, равно как и окружение try-catch

//    @Test(expected = java.io.FileNotFoundException.class)
//    public void testy() //throws FileNotFoundException
//    {
//        String[] lists1 = {"1,2,3,1,4,5", "1,2,7"};
//        String[] io1 = {".\\\\reading1.1.txt .\\\\reading1.2.txt .\\\\writing1.txt"};
//
//            assertArrayEquals("[3, 4, 5, 7]",Main.test(lists1));
//
//
//        }


    }


